### ISSUE TITLE
eating a melon popsicle causes a ticking player crash

### ISSUE THREAD

**Issue by notandvm** [newhoryzon/farmers-delight-fabric#176]
no other food items seem to have this issue, only the melon popsicle
1.20.1 instance with only fabric api & farmer's delight installed

crash log:
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-07-15 19:22:19
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
	at net.minecraft.class_1799.<init>(class_1799.java:169)
	at net.minecraft.class_1799.<init>(class_1799.java:152)
	at com.nhoryzon.mc.farmersdelight.item.ConsumableItem.method_7861(ConsumableItem.java:67)
	at net.minecraft.class_1799.method_7910(class_1799.java:288)
	at net.minecraft.class_1309.method_6040(class_1309.java:3144)
	at net.minecraft.class_3222.method_6040(class_3222.java:1176)
	at net.minecraft.class_1309.method_37119(class_1309.java:3023)
	at net.minecraft.class_3222.method_37119(class_3222.java:1699)
	at net.minecraft.class_1309.method_6076(class_1309.java:3010)
	at net.minecraft.class_1309.method_5773(class_1309.java:2381)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1799.<init>(class_1799.java:169)
	at net.minecraft.class_1799.<init>(class_1799.java:152)
	at com.nhoryzon.mc.farmersdelight.item.ConsumableItem.method_7861(ConsumableItem.java:67)
	at net.minecraft.class_1799.method_7910(class_1799.java:288)
	at net.minecraft.class_1309.method_6040(class_1309.java:3144)
	at net.minecraft.class_3222.method_6040(class_3222.java:1176)
	at net.minecraft.class_1309.method_37119(class_1309.java:3023)
	at net.minecraft.class_3222.method_37119(class_3222.java:1699)
	at net.minecraft.class_1309.method_6076(class_1309.java:3010)
	at net.minecraft.class_1309.method_5773(class_1309.java:2381)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 27
	Entity Name: notandvm
	Entity's Exact location: 0.09, -60.00, -5.06
	Entity's Block location: World: (0,-60,-6), Section: (at 0,4,10 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.13.0-valve36-1-neptune
	Java Version: 17.0.7, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 801299456 bytes (764 MiB) / 2155872256 bytes (2056 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0405
	Identifier: AuthenticAMD Family 23 Model 144 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: VanGogh [AMD Custom GPU 0405]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x163f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 22281.30
	Virtual memory used (MB): 7312.37
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 10.25
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['notandvm'/27, l='ServerLevel[New World]', x=0.09, y=-60.00, z=-5.06]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1
```

**Comment by Zifiv** [comment]
Hello @notandvm,

Thanks your for reporting this issue. I've already did a fix, it will be present in a next bugfix release.

**Comment by gamerpotion** [comment]
Hey, just wondering if you had a ETA on that fix release? getting a lot of my users reporting this issue to me with the crashing popsicle. Thanks

**Comment by Zifiv** [comment]
Hey @gamerpotion,

A release will be done this week-end (saturday or sunday).

**Comment by gamerpotion** [comment]
amazing thank you!! :)
