### ISSUE TITLE
Game crashes while eating watermelon popsicles

### ISSUE THREAD

**Issue by YTZHrain** [newhoryzon/farmers-delight-fabric#190]
1.20.1fabric
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2023-08-06 13:12:39
Description: Ticking player

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
at net.minecraft.class_1799.<init>(class_1799.java:169)
at net.minecraft.class_1799.<init>(class_1799.java:152)
at com.nhoryzon.mc.farmersdelight.item.ConsumableItem.method_7861(ConsumableItem.java:67)
at net.minecraft.class_1799.method_7910(class_1799.java:288)
at net.minecraft.class_1309.method_6040(class_1309.java:3144)
at net.minecraft.class_3222.method_6040(class_3222.java:1176)
at net.minecraft.class_1309.method_37119(class_1309.java:3023)
at net.minecraft.class_3222.method_37119(class_3222.java:1699)
at net.minecraft.class_1309.method_6076(class_1309.java:3010)
at net.minecraft.class_1309.method_5773(class_1309.java:2381)
at net.minecraft.class_1657.method_5773(class_1657.java:283)
at net.minecraft.class_3222.method_14226(class_3222.java:510)
at net.minecraft.class_3244.method_18784(class_3244.java:269)
at net.minecraft.class_2535.method_10754(class_2535.java:259)
at net.minecraft.class_3242.method_14357(class_3242.java:172)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
at net.minecraft.class_1132.method_3748(class_1132.java:105)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.class_1799.<init>(class_1799.java:169)
at net.minecraft.class_1799.<init>(class_1799.java:152)
at com.nhoryzon.mc.farmersdelight.item.ConsumableItem.method_7861(ConsumableItem.java:67)
at net.minecraft.class_1799.method_7910(class_1799.java:288)
at net.minecraft.class_1309.method_6040(class_1309.java:3144)
at net.minecraft.class_3222.method_6040(class_3222.java:1176)
at net.minecraft.class_1309.method_37119(class_1309.java:3023)
at net.minecraft.class_3222.method_37119(class_3222.java:1699)
at net.minecraft.class_1309.method_6076(class_1309.java:3010)
at net.minecraft.class_1309.method_5773(class_1309.java:2381)
at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
Entity Type: minecraft:player (net.minecraft.class_3222)
Entity ID: 245
Entity Name: Wallflower_P
Entity's Exact location: 9.50, 74.00, 3.50
Entity's Block location: World: (9,74,3), Section: (at 9,10,3 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Entity's Momentum: 0.00, -0.08, 0.00
Entity's Passengers: []
Entity's Vehicle: null
Stacktrace:
at net.minecraft.class_3222.method_14226(class_3222.java:510)
at net.minecraft.class_3244.method_18784(class_3244.java:269)
at net.minecraft.class_2535.method_10754(class_2535.java:259)
at net.minecraft.class_3242.method_14357(class_3242.java:172)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
at net.minecraft.class_1132.method_3748(class_1132.java:105)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
at java.base/java.lang.Thread.run(Thread.java:833)

Fabric Mods:
fabric-api: Fabric API 0.86.1+1.20.1
fabric-api-base: Fabric API Base 0.4.30+7abfd51577
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
fabricloader: Fabric Loader 0.14.21
farmersdelight: Farmer's Delight 1.20.1-1.4.1
java: Java HotSpot(TM) 64-Bit Server VM 17
minecraft: Minecraft 1.20.1
Server Running: true
Player Count: 1 / 8; [class_3222['Wallflower_P'/245, l='ServerLevel[新的世界]', x=9.50, y=74.00, z=3.50]]
Data Packs: vanilla, fabric
Enabled Feature Flags: minecraft:vanilla
World Generation: Stable
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
Launched Version: 1.20.1-Fabric 0.14.21

**Comment by Zifiv** [comment]
Hello @YTZHrain,

Thank you for reporting this issue, but it's a bug that was already reported and will be fixed in next release.

See #176.
