### ISSUE TITLE
Updated and game crash

### ISSUE THREAD

**Issue by washinoboku** [newhoryzon/farmers-delight-fabric#55]
Got this crash after updating to 0.1.9

----------------------------------------

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expandeddelight'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: NOURISHED
	at com.ianm1647.expandeddelight.registry.ItemRegistry.meal(ItemRegistry.java:149)
	at com.ianm1647.expandeddelight.registry.ItemRegistry.registerItems(ItemRegistry.java:81)
	at com.ianm1647.expandeddelight.ExpandedDelight.onInitialize(ExpandedDelight.java:22)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)

[crash-2022-08-11_23.59.32-client.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/9313416/crash-2022-08-11_23.59.32-client.txt)

Hope this was useful

**Comment by Footage2-Amply-Pounce** [comment]
Expanded Delight (and Farmer's Knives, if you have it) have to be updated.

**Comment by Zifiv** [comment]
Hello @washinoboku, like @Footage2-Amply-Pounce said, Expanded Delight need to be updated by his developer to be compatible with the last version of Farmer's Delight fabric.

**Comment by washinoboku** [comment]
i'm sorry i've mistaken the mods github page. i'll  posting in the correct tracker issue mod. thanks for answer me anyway.
