### ISSUE TITLE
Not working on 1.19.2

### ISSUE THREAD

**Issue by Skelun** [newhoryzon/farmers-delight-fabric#58]
Here's the output log:

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Farmer's Delight' (farmersdelight) 1.19-1.3.1 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Farmer's Delight' (farmersdelight) 1.19-1.3.1 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Zifiv** [comment]
Hello @Skelun, this is normal, the mod wasn't compatible in 1.19.2 for the moment, the version will come soon.
