### ISSUE TITLE
NullPointerException causes game crash

### ISSUE THREAD

**Issue by DroidQAQ** [newhoryzon/farmers-delight-fabric#64]
java.lang.NullPointerException: Cannot read field "field_6002" because "player" is null
	at net.minecraft.class_1799.handler$enb000$onDamage(class_1799.java:11661)
	at net.minecraft.class_1799.method_7970(class_1799.java)
	at net.minecraft.class_5168.method_10135(class_5168.java:31)
	at net.minecraft.class_2347.dispense(class_2347.java:16)
	at com.nhoryzon.mc.farmersdelight.entity.block.dispenser.CuttingBoardDispenseBehavior.method_10135(CuttingBoardDispenseBehavior.java:36)
	at net.minecraft.class_2347.dispense(class_2347.java:16)
	at net.minecraft.class_2315.method_10012(class_2315.java:90)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:943)
	at net.minecraft.class_3218.method_14189(class_3218.java:700)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[crash-2022-08-23_23.04.21-server.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/9404107/crash-2022-08-23_23.04.21-server.txt)

**Comment by Zifiv** [comment]
Hello @DroidQAQ, do you have any information about what can causes this. Usage of dispenser apparently, but with which item in it ?

After my first research, I understand that isn't Farmer's Delight that cause the error, because the line that is mentioned (line 36 of CuttingBoardDispenseBehavior.java) call the original method of a dispenser. Can you try to remove Farmer's Delight from your modpack to see if the game crash anyway.

**Comment by DroidQAQ** [comment]
Thank you for your prompt attention. The problem still occurred after I tried to remove it.
