### ISSUE TITLE
NullPointerException when starting server with Gobber2

### ISSUE THREAD

**Issue by spoorn** [newhoryzon/farmers-delight-fabric#94]
Fabric 1.19.2
Fabric Loader 0.14.10
Updated Farmer's Delight from 1.3.5 to 1.3.6 and got these errors when trying to start my modpack.  I see Gobber2 and MoonlightLib in the stacktrace

Log: 

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1291.method_42127()" because "$$0" is null
	at net.minecraft.entity.effect.StatusEffectInstance.<init>(StatusEffectInstance:51) ~[?:?]
	at net.minecraft.entity.effect.StatusEffectInstance.<init>(StatusEffectInstance:47) ~[?:?]
	at net.minecraft.entity.effect.StatusEffectInstance.<init>(StatusEffectInstance:43) ~[?:?]
	at com.nhoryzon.mc.farmersdelight.item.enumeration.Foods.<clinit>(Foods.java:17) ~[farmers-delight-fabric-1.19.X-1.3.6.jar:?]
	at com.nhoryzon.mc.farmersdelight.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:140) ~[farmers-delight-fabric-1.19.X-1.3.6.jar:?]
	at net.minecraft.item.ItemStack.<clinit>(ItemStack:126) ~[?:?]
	at net.minecraft.item.ItemGroup.<init>(ItemGroup:114) ~[?:?]
	at net.minecraft.class_1761$1.<init>(class_1761.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.item.ItemGroup.<clinit>(ItemGroup:15) ~[?:?]
	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder.build(FabricItemGroupBuilder.java:167) ~[fabric-item-groups-v0-0.3.33+70efcffe90-d8fd01933e690735.jar:?]
	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder.build(FabricItemGroupBuilder.java:158) ~[fabric-item-groups-v0-0.3.33+70efcffe90-d8fd01933e690735.jar:?]
	at com.kwpugh.gobber2.Gobber2.<clinit>(Gobber2.java:21) ~[Gobber2-Fabric-1.19.2-2.6.61.jar:?]
	at net.minecraft.entity.attribute.EntityAttributes.modify$enc000$gobberModifyMax(EntityAttributes:525) ~[?:?]
	at net.minecraft.entity.attribute.EntityAttributes.<clinit>(EntityAttributes:14) ~[?:?]
	at net.minecraft.entity.effect.StatusEffects.<clinit>(StatusEffects:15) ~[?:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks:237) ~[?:?]
	at net.minecraft.item.Items.<clinit>(Items:21) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.fluids.FoodProvider.<clinit>(FoodProvider.java:33) ~[moonlight-1.19.2-2.1.10-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.SoftFluid$Builder.<init>(SoftFluid.java:243) ~[moonlight-1.19.2-2.1.10-fabric.jar:?]
	at net.mehvahdjukaar.moonlight.api.fluids.fabric.SoftFluidRegistryImpl.getDefaultValue(SoftFluidRegistryImpl.java:81) ~[moonlight-1.19.2-2.1.10-fabric.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:161) ~[fabric-loader-0.14.10-1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) ~[fabric-loader-0.14.10-1.19.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 2 more
```

**Comment by Zifiv** [comment]
Hello @spoorn,

After my first investigation, it's caused by Gobber, because after adding Moonlight Lib without Gobber, it works well.
I'm trying to investigate and understand if it's an bug that Farmer's Delight should fix or if it's in Gobber author scope.

**Comment by Zifiv** [comment]
After more investigation I can add a fix in Farmer's Delight, it seems to be an error in the method I add food components in Farmer's Delight.
